language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

env:
  global:
    - secure: "bOaIYRw/IEDte06WCUq6vDcUmPpxT9wm2qXOSfXkYBKGlMHno0Nt7K1K2A8ZmhOHMPT2wbTm0+9IwdZ8kZDpf0Y47T39L7RImCEDz7bUZnI289wvKnNWaXClmmRye+uXQX8wIRrI31o44J654/0HcVwG9cyhTazR8wui1du3r60="

after-success: "make selenium"
